[project]
name = "AutoContainerMod"
version = "1.0.81"
description = "Automatically opens containers (chests, lockers, etc.) when you get close to them.\nConfigurable range.\n"
[[project.authors]]
name = "galqawala"

[tool.sdkmod]
name = "AutoContainerMod"
supported_games = [ "BL1", "BL1E",]
coop_support = "ClientSide"
download = "https://github.com/galqawala/AutoContainerMod/raw/refs/heads/master/AutoContainerMod.sdkmod"

[tool.sdkmod.license]
name = "GPL3"
url = "https://choosealicense.com/licenses/gpl-3.0/"
